name: Scrape latest data

on:
  schedule:
    - cron: '*/30 * * * *'

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2

      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: npm
      
      - name: Install Node dependencies
        run: npm install

      - name: Fetch latest data
        run: npm run scrape

      - name: Commit and push if changed
        run: |-
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          timestamp=$(date -u)
          git commit -m "Latest data: ${timestamp}" || exit 0
          git push
